version: '3.7'

services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data/logs.txt:/app/dist/logs.txt
      - ./data/storage.json:/app/dist/storage.json
    ports:
      - '3000:3000'